spring.application.name=vagarin-api

spring.datasource.url=jdbc:postgresql://localhost:5432/vagarin
spring.datasource.username=vagarin
spring.datasource.password=vagarin

spring.jpa.hibernate.ddl-auto=update

# (Opcional) Mostra o SQL que o Spring está rodando no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
server.address=0.0.0.0

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.web=DEBUG
