spring.application.name=vagarin-api

# --- Configuração do Banco de Dados (Postgres) ---
# A URL aponta para o container Docker que você subiu no Passo 2
spring.datasource.url=jdbc:postgresql://localhost:5432/vagarin
spring.datasource.username=vagarin
spring.datasource.password=vagarin

# --- Configuração do JPA (Hibernate) ---
# Isso aqui é MÁGICA:
# "update" = O Spring vai ler suas classes Java (@Entity) e criar
# ou atualizar as tabelas no banco de dados SOZINHO.
# Você não vai precisar escrever SQL de "CREATE TABLE".
spring.jpa.hibernate.ddl-auto=update

# (Opcional) Mostra o SQL que o Spring está rodando no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true